// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKJNLocgLRbmjYgBkNtECtNcV__vhOeRg',
    appId: '1:1017929720223:web:85f0e81e03fc13191fddaa',
    messagingSenderId: '1017929720223',
    projectId: 'catalog-checkout-uts-83012',
    authDomain: 'catalog-checkout-uts-83012.firebaseapp.com',
    storageBucket: 'catalog-checkout-uts-83012.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl6TwuI4C58LqUFbTqBrFo8imlUxn8aA0',
    appId: '1:1017929720223:android:eec6f88f77a8ac121fddaa',
    messagingSenderId: '1017929720223',
    projectId: 'catalog-checkout-uts-83012',
    storageBucket: 'catalog-checkout-uts-83012.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlNpt_27wkIByPW3CUknZITnLKVZCkkRc',
    appId: '1:1017929720223:ios:578b404006e8c2e61fddaa',
    messagingSenderId: '1017929720223',
    projectId: 'catalog-checkout-uts-83012',
    storageBucket: 'catalog-checkout-uts-83012.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlNpt_27wkIByPW3CUknZITnLKVZCkkRc',
    appId: '1:1017929720223:ios:578b404006e8c2e61fddaa',
    messagingSenderId: '1017929720223',
    projectId: 'catalog-checkout-uts-83012',
    storageBucket: 'catalog-checkout-uts-83012.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKJNLocgLRbmjYgBkNtECtNcV__vhOeRg',
    appId: '1:1017929720223:web:b82224e06078eccc1fddaa',
    messagingSenderId: '1017929720223',
    projectId: 'catalog-checkout-uts-83012',
    authDomain: 'catalog-checkout-uts-83012.firebaseapp.com',
    storageBucket: 'catalog-checkout-uts-83012.firebasestorage.app',
  );
}
